=head1 NAME

Class::VirtualAccessor - object variable access supporter

=head1 SYNOPSIS

  use Class::VirtualAccessor (
    rw => [qw/hoge fuga/],
    ro => [qw/foo/],
  );

  sub new {
      my $class = shift;
      my $args  = (@_ == 1) ? $_[0] : +{ @_ };

      vbless(+{ %$args } => $class);

      # or you can use this interface
      # bless(+{ %$args } => $class)->with_vaccessor;
  }

  sub method {
      my $self = shift;

      $self->{hoge} = 'hogehoge';   # ok
      $self->{hoga} = 'hogehoge';   # typo! error!
      $self->{foo}  = 'hogehoge';   # can't write! error!
  }

=head1 DESCRIPTION

Class::VirtualAccessor is 

=head1 AUTHOR

Kenta Sato E<lt>karupa@cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

